# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EventApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod ‘Firebase/Auth’
  pod ‘Firebase/Database’
  pod ’Stripe’
  pod 'Alamofire’, ‘~> 4.0’
  pod 'Firebase/Storage'
  # Pods for EventApp

  target 'EventAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EventAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
